name: image_formation_whatever
channels:
  - defaults
  - conda-forge
dependencies:
  - py-openimageio>=2.1.10
  - libgcc
  - cmake
  - git
  - pkg-config
  - freetype
  - libpng
  - pip:
    - opencolorio>=2.1.0
    - numpy
    - colour-science>=0.3.16
    - glom
    - streamlit>=0.88.0
    - gdown
    - matplotlib
    - fs